# Generated by Django 3.1.5 on 2021-01-18 10:26

import courses.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20210109_0059'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(default='images/default.png', upload_to=courses.utils.course_image),
        ),
    ]
